common-params:
  &publish-android-artifacts-docker-container
  docker#v3.8.0:
    image: "public.ecr.aws/automattic/android-build-image:v1.1.0"
    propagate-environment: true
    environment:
      # DO NOT MANUALLY SET THESE VALUES!
      # They are passed from the Buildkite agent to the Docker container
      - "AWS_ACCESS_KEY"
      - "AWS_SECRET_KEY"

steps:
  - label: "ktlint"
    plugins:
      - *publish-android-artifacts-docker-container
    command: |
      ./gradlew ciktlint
    artifact_paths:
      - "**/build/ktlint.xml"
  - label: "Assemble Release"
    plugins:
      - *publish-android-artifacts-docker-container
    command: |
      ./gradlew assembleRelease
  - label: "Publish :mediapicker"
    key: "publish-mediapicker"
    plugins:
      - *publish-android-artifacts-docker-container
    command: |
      .buildkite/publish-mediapicker.sh
  - label: "Publish :mediapicker:domain"
    key: "publish-domain"
    plugins:
      - *publish-android-artifacts-docker-container
    command: |
      .buildkite/publish-domain.sh
  - label: "Publish :mediapicker:source-device"
    key: "publish-source-device"
    plugins:
      - *publish-android-artifacts-docker-container
    command: |
      .buildkite/publish-source-device.sh