common-params:
  &docker-container
  docker#v3.8.0:
    image: "public.ecr.aws/automattic/android-build-image:v1.1.0"
    propagate-environment: true

steps:
  - label: "ktlint"
    plugins:
      - *docker-container
    command: |
      ./gradlew ciktlint
    artifact_paths:
      - "**/build/ktlint.xml"
  - label: "lint"
    plugins:
      - *docker-container
    command: |
      ./gradlew lintRelease
    artifact_paths:
      - "**/build/reports/lint-results*.*"
  - label: "Unit test"
    plugins:
      - *docker-container
    command: |
      ./gradlew testRelease
  - label: "Assemble Release"
    plugins:
      - *docker-container
    command: |
      ./gradlew assembleRelease
