common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.11.0

steps:
  - label: "ktlint"
    key: "ktlint"
    plugins: *common_plugins
    command: |
      ./gradlew ciktlint
    artifact_paths:
      - "**/build/ktlint.xml"
  - label: "lint"
    key: "lint"
    plugins: *common_plugins
    command: |
      ./gradlew lintRelease
    artifact_paths:
      - "**/build/reports/lint-results*.*"
  - label: "Unit test"
    key: "unit-test"
    plugins: *common_plugins
    command: |
      ./gradlew testRelease

  # Publish tasks
  - label: "Publish :mediapicker:domain"
    key: "publish-mediapicker-domain"
    depends_on:
      - "ktlint"
      - "lint"
      - "unit-test"
    plugins: *common_plugins
    command: |
      .buildkite/publish-mediapicker-domain.sh
  - label: "Publish :mediapicker:source-device"
    depends_on:
      - "publish-mediapicker-domain"
    plugins: *common_plugins
    command: |
      .buildkite/publish-mediapicker-source-device.sh
  - label: "Publish :mediapicker:source-gif"
    depends_on:
      - "publish-mediapicker-domain"
    plugins: *common_plugins
    command: |
      .buildkite/publish-mediapicker-source-gif.sh
  - label: "Publish :mediapicker:source-wordpress"
    depends_on:
      - "publish-mediapicker-domain"
    plugins: *common_plugins
    command: |
      .buildkite/publish-mediapicker-source-wordpress.sh
  - label: "Publish :mediapicker"
    depends_on:
      - "publish-mediapicker-domain"
    plugins: *common_plugins
    command: |
      .buildkite/publish-mediapicker.sh
