docker-container: &docker-container
  plugins:
    - docker#v3.8.0:
        image: "public.ecr.aws/m4u4m2y0/android-build-image:latest"
        environment:
          - "CI=true"

steps:
  - label: "ktlint"
    <<: *docker-container
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew ciktlint
  - label: "lint"
    <<: *docker-container
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew lintRelease
  - label: "Unit test"
    <<: *docker-container
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew testRelease
  - label: "Assemble Release"
    <<: *docker-container
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew assembleRelease
